version: '3.4'

services:
    db:
        image: redis:6.0
        ports:
            - 6379:6379

    api:
        build:
            context: ./
            dockerfile: ./Dockerfile.api
        environment: 
            - REDIS_HOST=db
            - REDIS_PORT=6379
            - API_HOST=0.0.0.0
            - API_PORT=8080

        ports:
            - 8080:8080
        depends_on: ['db']

    websocket_server:
        build: 
            context: ./
            dockerfile: ./Dockerfile.socket_server
        environment: 
            - REDIS_HOST=db
            - REDIS_PORT=6379
            - SOCKET_HOST=0.0.0.0
            - SOCKET_PORT=3000
        ports:
            - 3000:3000
        depends_on: ['db']
